_Screen.Caption = _Screen.Caption + " (" + VERSION(4) + ")"
?"Please run the command: FoxBin2Prg testcom.pj2 *"
?"Then restart the session with administrative privileges"
?"Open Project Explorer, and build to an EXE"
?""
?""
?"For test purposes I compile to the bin folder."
?"The bin folder is ignored in the .gitignore file"
?""
?""
?"Since a compile writes to the registry."
?"Remember to clean up the registry before deleting with the following:"
?"testcom.exe /unregserver"